dataset:
  path: "example/dataset/2025_AllSites_Orig.parquet"

# Configuration for DataLoader and Training
preprocessing:
  lags: 24                   # lags window
  horizon: 8                 # future time window
  ids: [0]          # List of sites to preprocess in the dataset
  features: 1                # Number of features per timestep
  channels: 1                # Number of channels in the target output

dataloader:
  batch_size: 32             # Batch size for DataLoader
  shuffle: true              # Shuffle training data

model:
  name: nbeats
  input_size: 33         
  hidden_size: 64      # Number of neurons in each hidden layer
  output_size: 8        # Forecast horizon
  num_blocks: 4          # Number of stacked blocks
  save_path: "example/results/models/nbeats.pth"


device:
  type: cpu                 # Device to run the tensors on ('cpu' or 'cuda')

training:
  learning_rate: 0.001       # Learning rate for the optimizer
  epochs: 2                 # Number of training epochs
  scheduler_gamma: 0.1       # Factor to reduce the learning rate
  scheduler_patience: 5      # Number of epochs to wait before reducing LR
